### ISSUE TITLE
Should call `provider.engine.stop()` at termination

### ISSUE THREAD

**Issue by SantonyChoi** [trufflesuite/truffle-hdwallet-provider#46]
I found using this provider in general usage makes the whole program hang at the end.
It's because `stop` is not called at anywhere in this provider's implementation.
So, I suggest add some guide to induce users to call `provider.engine.stop` explicitly.

**Comment by hellwolf** [comment]
Due to this, I cannot use this version (0.0.5) of truffle-hdwallet-provider at all for ropsten testnet:

One problem for the least, when using truffle test:
- truffle compile starts with this provider created, which calls the engine.start()
- since engine.stop is never called, the compile phase never finishes, and truffle test hangs forever.

**Comment by kyriediculous** [comment]
What is not immeadiatly clear is wether this should becalled at the end of migrations and executions or in the truffle-config file at the end. Any suggestions? Thank you !

**Comment by SantonyChoi** [comment]
@kyriediculous This issue is about General usage of this library and I think you are talking about truffle usage(https://github.com/trufflesuite/truffle-hdwallet-provider#truffle-usage). In my case, Truffle terminated programs somehow without `engine.stop` call.

**Comment by kyriediculous** [comment]
No I'm not. I'm talking about the fact that the "added guide" provides no context at all.

**Comment by fjcadenas** [comment]
Hello, this seems quite cold now. Any news ? I someone else having this same problem ?

Thank you!

**Comment by SantonyChoi** [comment]
I will close this issue since this repo has been deprecated.

Thanks!
